# Generated by Django 3.2.9 on 2024-03-23 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_alter_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('customer_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('cust_acc_num', models.CharField(blank=True, max_length=20, unique=True)),
                ('rec_acc_num', models.CharField(blank=True, max_length=20, unique=True)),
                ('account_type', models.CharField(blank=True, max_length=50)),
                ('cust_old_bal', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cust_new_bal', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('rec_old_bal', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('rec_new_bal', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('bio', models.TextField(blank=True)),
                ('profileimg', models.ImageField(default='blank-profile-picture.png', upload_to='profile_images')),
                ('location', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
