# Generated by Django 3.1.8 on 2023-02-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20230217_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbankaccount',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
